services:
  - type: web
    name: ufo-news-desk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - fromDatabase:
          name: ufo-db
          property: connectionString
        key: DATABASE_URL

databases:
  - name: ufo-db